### ISSUE TITLE
Request: concurrent network requests (XL work)

### ISSUE THREAD

**Issue by sdsantos** [blockstack/blockstack-android#154]
I'm trying to upload a large file in multiple parts, and making those requests run in parallel would make that task faster. But with the current implementation all requests are bottlenecked by a single V8 thread.

Is there any easier solution than having multiple Blockstack sessions, if that's even possible and not consume too many resources? Or is this a shortcoming of the current library?

**Comment by friedger** [comment]
There are limitations due to the j2v8. For multiple Blockstack sessions/threads to work you need to attach and detach the engine (there are methods for that), not sure what will happen with the running upload calls or the return results. It looks like difficult to manage.

I think it would make more sense to implement putFile in Android directly.

**Comment by sdsantos** [comment]
@friedger a native Android library, or even just the `putFile` call, sounds like a dream. I haven't look much inside the `blockstack.js`, but I imagine it's no small task.

**Comment by friedger** [comment]
Gaia protocol is not that difficult...

**Comment by friedger** [comment]
Work is done in feature branch `native_gaia`

**Comment by friedger** [comment]
Version 0.5.0 introduces a native implementation of the gaia protocol, giving much more control over concurrent requests.
